import chatService from '../../services/chat/chat';
import { storage, KEYS } from '../../utils/storage/storage';
import { formatTime } from '../../utils/request/request';
import lazyLoader from '../../utils/lazyload/lazyload';

Page({
  data: {
    messages: [],
    currentAssistantMessage: '',
    loading: false,
    sessionId: '', // get from globalData or storage if needed
    useWebSocket: true, // can be toggled in settings
    scrollToId: ''
  },

  onLoad() {
    // Load chat history from storage
    const history = storage.get(KEYS.CHAT_HISTORY) || [];
    this.setData({ messages: history });
    
    // Set initial mode
    chatService.setMode(this.data.useWebSocket);
    
    // Scroll to bottom after loading messages
    if (history.length > 0) {
      this.scrollToBottom();
    }
    
    // Initialize lazy loading after a delay
    setTimeout(() => {
      this.initLazyLoading();
    }, 1000);
  },

  async initLazyLoading() {
    try {
      // Initialize image lazy loading only if we have images
      // For chat page, we might add avatar images or shared images later
      setTimeout(async () => {
        await lazyLoader.initImageLazyLoadSafe('.lazy-image', this);
      }, 500); // Wait for DOM to be ready
      
      // Lazy load components that aren't immediately visible
      lazyLoader.loadComponent('chat-components', () => {
        // Chat components loaded successfully
      });
         } catch (error) {
       console.error('[Chat] Lazy loading initialization error:', error);
     }
  },

  async loadChatHistory() {
    // Show skeleton loading state
    this.setData({ 
      loading: true,
      messages: [] 
    });

    try {
      // Simulate lazy loading of chat history
      const history = await lazyLoader.loadData(
        () => {
          return new Promise(resolve => {
            setTimeout(() => {
              const data = storage.get(KEYS.CHAT_HISTORY) || [];
              resolve(data);
            }, 200); // Small delay to show loading state
          });
        },
        'chat_history'
      );

      this.setData({ 
        messages: history,
        loading: false 
      });

      // Scroll to bottom after loading messages
      if (history.length > 0) {
        this.scrollToBottom();
      }
    } catch (error) {
      console.error('Failed to load chat history:', error);
      this.setData({ loading: false });
    }
  },

  onShow() {
    // Setup share menu and other options
    wx.showShareMenu({
      withShareTicket: true,
      menus: ['shareAppMessage', 'shareTimeline']
    });
  },

  onShareAppMessage() {
    return {
      title: 'DeepSeek Chat - AI Assistant',
      path: '/pages/chat/chat',
      imageUrl: '/assets/images/chat_share.svg' // Share image for DeepSeek Chat
    };
  },

  // Menu options when user taps the menu button
  onMenuButtonTap() {
    const that = this;
    wx.showActionSheet({
      itemList: [
        'Clear Chat History',
        'Switch to ' + (this.data.useWebSocket ? 'HTTP' : 'WebSocket') + ' Mode',
        'Share Chat',
        'About'
      ],
      success: function(res) {
        switch(res.tapIndex) {
          case 0:
            that.clearChat();
            break;
          case 1:
            that.toggleMode();
            break;
          case 2:
            that.shareChat();
            break;
          case 3:
            that.showAbout();
            break;
        }
      }
    });
  },

  shareChat() {
    const that = this;
    
    // If no messages, just share the mini-program
    if (this.data.messages.length === 0) {
      wx.showShareMenu({
        withShareTicket: true
      });
      return;
    }

    // Show options for sharing
    wx.showActionSheet({
      itemList: [
        'Share Mini-Program',
        'Copy Chat Summary',
        'Share Last Answer'
      ],
      success: function(res) {
        switch(res.tapIndex) {
          case 0:
            // Share the mini-program
            wx.showShareMenu({
              withShareTicket: true
            });
            break;
          case 1:
            // Copy chat summary to clipboard
            that.copyChatSummary();
            break;
          case 2:
            // Share the last assistant response
            that.shareLastAnswer();
            break;
        }
      }
    });
  },

  copyChatSummary() {
    if (this.data.messages.length === 0) {
      wx.showToast({
        title: 'No messages to share',
        icon: 'none'
      });
      return;
    }

    // Create a summary of the conversation
    let summary = '💬 DeepSeek Chat Summary\n\n';
    this.data.messages.slice(-3).forEach((msg, index) => {
      const prefix = msg.role === 'user' ? '👤 You: ' : '🤖 AI: ';
      const content = msg.content.substring(0, 100) + (msg.content.length > 100 ? '...' : '');
      summary += prefix + content + '\n\n';
    });
    
    summary += '🔗 Generated by DeepSeek Chat Mini-Program';

    wx.setClipboardData({
      data: summary,
      success: () => {
        wx.showToast({
          title: 'Chat summary copied!',
          icon: 'success'
        });
      }
    });
  },

  shareLastAnswer() {
    const lastMessage = this.data.messages[this.data.messages.length - 1];
    
    if (!lastMessage || lastMessage.role !== 'assistant') {
      wx.showToast({
        title: 'No AI response to share',
        icon: 'none'
      });
      return;
    }

    const shareText = `🤖 AI Response:\n\n${lastMessage.content}\n\n🔗 From DeepSeek Chat`;
    
    wx.setClipboardData({
      data: shareText,
      success: () => {
        wx.showToast({
          title: 'AI response copied!',
          icon: 'success',
          duration: 2000
        });
        
        // Show hint about sharing
        setTimeout(() => {
          wx.showToast({
            title: 'You can now paste and share!',
            icon: 'none',
            duration: 2000
          });
        }, 2500);
      }
    });
  },

  showAbout() {
    wx.showModal({
      title: 'About DeepSeek Chat',
      content: 'DeepSeek Chat is an AI-powered assistant. Version 1.0\n\nDeveloped for WeChat Mini-Program platform.',
      showCancel: false,
      confirmText: 'OK'
    });
  },

  onUnload() {
    // Save chat history to storage
    storage.set(KEYS.CHAT_HISTORY, this.data.messages);
    
    // Clean up lazy loader for this page
    lazyLoader.destroy();
  },

  // Helper method to ensure smooth scrolling to bottom
  scrollToBottom() {
    // Use timeout to ensure DOM has updated
    setTimeout(() => {
      this.setData({ scrollToId: 'bottom-anchor' });
    }, 100);
    
    // Additional scroll after a longer delay to catch any final content
    setTimeout(() => {
      this.setData({ scrollToId: '' });
      setTimeout(() => {
        this.setData({ scrollToId: 'bottom-anchor' });
      }, 50);
    }, 300);
  },

  async onSend(e) {
    const content = e.detail.content;
    if (!content || !content.trim()) return;
    this.setData({ loading: true, currentAssistantMessage: '' });

    if (this.data.useWebSocket) {
      // WebSocket mode
      const userMsg = { role: 'user', content };
      this.data.messages.push(userMsg);
      this.setData({ messages: this.data.messages });
      this.scrollToBottom();
      storage.set(KEYS.CHAT_HISTORY, this.data.messages);

      chatService.sendMessage({
        sessionId: this.data.sessionId,
        message: content,
        onToken: (token) => {
          this.setData({
            currentAssistantMessage: this.data.currentAssistantMessage + token
          });
          this.scrollToBottom();
        },
        onDone: () => {
          const assistantMsg = { role: 'assistant', content: this.data.currentAssistantMessage };
          this.data.messages.push(assistantMsg);
          this.setData({ messages: this.data.messages, currentAssistantMessage: '', loading: false });
          this.scrollToBottom();
          storage.set(KEYS.CHAT_HISTORY, this.data.messages);
        },
        onError: (err) => {
          wx.showToast({ title: err, icon: 'none' });
          this.setData({ loading: false, currentAssistantMessage: '' });
          this.scrollToBottom();
        }
      });
    } else {
      // HTTP mode
      chatService.sendMessage(content)
        .then(({ userMessage, assistantMessage }) => {
          this.data.messages.push(userMessage, assistantMessage);
          this.setData({ 
            messages: this.data.messages,
            loading: false
          });
          this.scrollToBottom();
          storage.set(KEYS.CHAT_HISTORY, this.data.messages);
        })
        .catch((err) => {
          wx.showToast({ title: err.message || 'Failed to send message', icon: 'none' });
          this.setData({ loading: false });
          this.scrollToBottom();
        });
    }
  },

  handleMessageTap(e) {
    const { message } = e.detail;
    // Handle message tap (e.g., copy to clipboard)
    wx.setClipboardData({
      data: message.content,
      success: () => {
        wx.showToast({
          title: 'Copied to clipboard',
          icon: 'success'
        });
      }
    });
  },

  clearChat() {
    wx.showModal({
      title: 'Clear Chat',
      content: 'Are you sure you want to clear all messages?',
      success: (res) => {
        if (res.confirm) {
          chatService.clearMessages();
          this.setData({ messages: [] });
          storage.remove(KEYS.CHAT_HISTORY);
          // Clear session ID from global data
          const app = getApp();
          app.globalData.sessionId = '';
          wx.reportAnalytics('chat_cleared', {});
        }
      }
    });
  },

  toggleMode() {
    const newMode = !this.data.useWebSocket;
    this.setData({ useWebSocket: newMode });
    chatService.setMode(newMode);
    wx.showToast({
      title: `Switched to ${newMode ? 'WebSocket' : 'HTTP'} mode`,
      icon: 'none'
    });
  }
}); 