version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - REQUEST_TIMEOUT=30
      - SHUTDOWN_TIMEOUT=10
      - ALLOWED_ORIGINS=http://localhost:3000
      - ALLOWED_METHODS=GET,POST,OPTIONS
      - ALLOWED_HEADERS=Content-Type,Authorization
      - SESSION_TIMEOUT=3600
      - MAX_SESSIONS=1000
    volumes:
      - .:/app
    command: go run main.go
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 